Revert "Bump github.com/compose-spec/compose-go from 1.15.0 to 1.16.0 (#43)" (#45)
This reverts commit 93f7d2e49b248b77a6a675543c00c1538e0b3dbb.

Previous PR created issues with code, e.g.: "../util/pmm.go:88:19: undefined: cli.GetEnvFromFile"